export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const TOKEN_EXPIRED = 'TOKEN_EXPIRED';
export const TOKEN_NOT_EXPIRED = 'TOKEN_NOT_EXPIRED';



export const USER_FETCHING = 'USER_FETCHING';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_FAILED = 'USER_FAILED';



export const CANDIDATE_FETCHING = 'CANDIDATE_FETCHING';
export const CANDIDATE_SUCCESS = 'CANDIDATE_SUCCESS';
export const CANDIDATE_FAILED = 'CANDIDATE_FAILED';







